# Generated by Django 4.0.3 on 2022-04-11 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turi', models.CharField(max_length=30)),
                ('narxi', models.PositiveSmallIntegerField()),
                ('rangli', models.BooleanField()),
                ('yangi', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='kitob',
            name='muallif',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='m_kitoblari', to='app1.muallif'),
        ),
    ]
