# Generated by Django 4.0.3 on 2022-04-12 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_printer_alter_kitob_muallif'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turi', models.CharField(max_length=30)),
                ('narxi', models.PositiveSmallIntegerField()),
                ('tezkor_xotirasi', models.BooleanField()),
                ('chiqrilgan_sanasi', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Telefon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=30)),
                ('modeli', models.CharField(max_length=30)),
                ('sanasi', models.DateField()),
            ],
        ),
    ]
